### ISSUE TITLE
Suggestion re UDP

### ISSUE THREAD

**Issue by JohnN6** [OddLingo/js8map#5]
It might be better to put the UDP Port no. at the top of the code as one of the in line parameters with a default as not everyone will use the port you have chosen - I use 2237 for compatibility with other software.

**Comment by OddLingo** [comment]
This has been fixed in the lated version.  Look for the symbol JS8PORT.

**Comment by JohnN6** [comment]
Thanks, I think it will make it much easierfor those ho don’t speak enough Python to go looking thru’ the code.

Personally I am unconventional, as I like to set up all my a variable parameters in an external CSV file if there are a lot of complex parameters , and then read them into a dictionary.  This has worked for me where I wanted to make soemthing to send out lots of intialisation parameters to transceivers - users can configure them easily via spreadsheets

IF there are only a small amount I have used the configparser module which gives gives text based .ini files.

John N.

**Comment by OddLingo** [comment]
I am adding a command-line option as well.  Eventually I will probably add a configuration file to remember all the settings.  Another thing I do is run things from short script files that supply all my favorite settings, like initial map boundaries.

**Comment by JohnN6** [comment]
It ( v 0.55 ) really looks good now.  It is mid afternoon here in London, UK and so there are  not many stations about on 7078KHz.   I am busy tonight with my XYL so won’t bea ble to report back to you.

I think I will try to adjust the period for which lines are drawn - my objective is to work out routing commands to go with the > method of forwarding so a map showing links over a 45+ minute period is useful for me.

Of course this may be part nostalgia for the old NETROM packet radio where the local TNC built up a learnt list of how to forward messages.  I am still having fun with JS8Call but regret that I don’t get any intercontinental DX.  I can exchange FT8 with the USA down to Chile most nights but not JS8Call.

Thanks for all your work from an appreciative fellow ham

John Newgas.
G7LTQ/AG7VS  Locator  IO91WN16
Direct email:   ***@***.***
